### ISSUE TITLE
Where is it stated that HLG sets the diffuse white point at 75%?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ColorWeb-CG#1]
Answer is the ITU HDR practice guidelines, citation to be confirmed.

**Comment by simontWork** [comment]
ITU-R BT.2408-1 Table 1 Lists reference white as 58% PQ and 75% HLG
https://www.itu.int/dms_pub/itu-r/opb/rep/R-REP-BT.2408-1-2018-PDF-E.pdf

**Comment by svgeesus** [comment]
(I need to add this to the CG report)

**Comment by svgeesus** [comment]
The same reference gives the luminance of graphics white as 203 cd/m^2, which is a much more reasonable aim value than 80 (sRGB). That would imply a TTML luminance factor of 203 / 80 = 2.5375

**Comment by nigelmegitt** [comment]
If I've understood this correctly, the 203 cd/m^2 figure is a nominal figure based on specific viewing conditions as shown in table 4 in that document, i.e. it applies only when the nominal peak luminance happens to be 1000 cd/m^2. 

Obviously it depends on the referencing context, but I'd suggest caution if you're thinking of using an absolute display luminance level for the HLG graphics white level rather than the relative 75% figure.

**Comment by simontWork** [comment]
That's correct.  The reference diffuse white value is 75% to allow for specular highlights.  This just happens to be 203 cd/m^2 on a reference HLG implementation when set up for viewing in a reference viewing environment.

The suggested sRGB to HLG transform in the working document does not use _TTML Luminance Factor_

**Comment by svgeesus** [comment]
This is now captured in the [CSS Color HDR]((https://drafts.csswg.org/css-color-hdr/) draft, for the [rec2100-hlg](https://drafts.csswg.org/css-color-hdr/#valdef-color-rec2100-hlg):

> The Hybrid Log-Gamma (HLG) electro-optical transfer function is used [ARIB_STD-B67],[Rec_BT.2100]. HLG can be used with displays of different brightness in a wide range of viewing environments, with user control of the overall brightness level. A value of 0.75 represents "diffuse" or "media" white while an "18% reflectance grey" card has a value of 0.38. [Rec_BT.2390].

and

>  Content is typically mastered with a peak white of 1,000 to 4,000 cd/m², so diffuse white will be 203 to 581 cd/m².

**Comment by svgeesus** [comment]
> Obviously it depends on the referencing context, but I'd suggest caution if you're thinking of using an absolute display luminance level for the HLG graphics white level rather than the relative 75% figure.

No, the CSS specification is clear that HLG is relative.
