### ISSUE TITLE
Request - Add Table To Summarize/Document Still Graphics Color Volume Signaling (Color Primaries, Transfer Functions, Matrix Coef.)

### ISSUE THREAD

**Issue by digitaltvguy** [w3c/ColorWeb-CG#10]
I would like to suggest the addition of a simple table that summarizes and consolidates still graphics color volume signaling (Color Primaries, Transfer Functions, Matrix Coef.).

I've started one and should have it ready to submit and would be happy if someone could review it and add detail from work that has been done in W3C already.

I've also requested info from ATSC, Sky to see if they're aware of other work that has been done here.

Thank you, Chris

**Comment by digitaltvguy** [comment]
[https://www.dropbox.com/s/sy2evvkxwyaauel/HDR%20Still%20Graphics%20Formats%20%26%20Signaling.xlsx?dl=0](url)

**Comment by digitaltvguy** [comment]
[https://www.dropbox.com/s/sy2evvkxwyaauel/HDR%20Still%20Graphics%20Formats%20%26%20Signaling.xlsx?dl=0](url)

**Comment by digitaltvguy** [comment]
First Effort:

https://www.dropbox.com/s/sy2evvkxwyaauel/HDR%20Still%20Graphics%20Formats%20%26%20Signaling.xlsx?dl=0

**Comment by digitaltvguy** [comment]
Here's 2nd attempt:

https://www.dropbox.com/s/ymtzbcni8sww2kb/HDR%20Still%20Graphics%20Formats%20%26%20Signaling%20v2.xlsx?dl=0

**Comment by lrosenthol** [comment]
@digitaltvguy did you want comments here?  On the DropBox file?  Elsewhere?

**Comment by digitaltvguy** [comment]
It sounds like we have a meeting with new idea's that might be more helpful to our workflows.  I will join tomorrow and likely update this table.  The goal would be to add this table to the HDR report when it represents the current status of HDR signaling in still graphics.

**Comment by lrosenthol** [comment]
To fill in a few ?'s
- Yes, TIFF is an Adobe proprietary, but published, specification
- TIFF uses ICC profiles, when present, for color management.
- PNG uses ICC profiles, when present, for color management.
- JP2K uses either ICC profiles, when present, or allows for internal colorspace specifications

**Comment by digitaltvguy** [comment]
Thanks Leonard.  I've added a column "Supports ICC Profiles" to support your information.  I've spoken with Lars about TIFF and there's an idea that I'm a proponent for in ICC that may help us address this issue more consistently.

**Comment by lrosenthol** [comment]
@digitaltvguy I am aware of Lars' proposal and he and I are not aligned on it...

**Comment by svgeesus** [comment]
Would this be similar to what is in [ITU-T H.273](https://www.itu.int/rec/T-REC-H.273/en) ?

**Comment by digitaltvguy** [comment]
ITU-T H.273 Documents the CICP values.  ITU-T H Supplement 19, is a sort of pocket guide that includes the common signaling formats for SDR/HDR/WCG formats for broadcast video with CICP values, but also SMPTE Unique Labels that are used in MXF files and SMPTE U/L’s for VPID’s that signal in SDI, and finally SMPTE U/L’s that signal in ST.2110 (IP Video).

It references over 47 different standards in one document.

I guess what I’m suggesting is that we have a similar table for still graphics which are surprisingly not defined.  I’d like to include it in ITU-T H Supplement (I’m one of the co-authors).

-Chris

**Comment by lrosenthol** [comment]
@digitaltvguy AVIF also supports ICC profiles as well (though it has a custom algo for when)

**Comment by digitaltvguy** [comment]
I think we can close this issue if we have a reference to the tables in ITU-T H.273 in W3C documentation

**Comment by digitaltvguy** [comment]
dfsdaf
