### ISSUE TITLE
Create new CICP chunk in PNG (See ITU-T H.273)

### ISSUE THREAD

**Issue by digitaltvguy** [w3c/ColorWeb-CG#11]
Can we add a chunk to the PNG standard which stores "Coding-independent code points for video signals" (CICP) so that graphics content identification can be identified the same way motion video images are?

This would prevent an issue where an ICC profile gets stripped from a file causing a loss of HDR/WCG signaling.

Color Primaries, Transfer Function and Matrix Coefficients are identified in Tables 2, 3 & 4 of ITU-T H.273.

We would also need to store signal range.  This requires 7 bytes according to Pierre.

**Comment by ProgramMax** [comment]
I currently have no objections to this. But I would like to impose a requirement on the CICP chunk: That it come before frame data.

Web browsers display images as they are being downloaded. If the image is fully displayed and then needs to change its color space, the user would experience a visual pop. Worse, maybe the image data is already sent to the GPU and cannot be read back, so the image needs to be decoded a second time with the new color profile (in addition to the visual pop).

**Comment by simontWork** [comment]
As discussed with Lars, we need to take care that a situation doesn't occur whereby we have a CICP chunk and and ICC profile with different data.

**Comment by svgeesus** [comment]
Related: [PNG maintenance and development](https://github.com/w3c/strategy/issues/58)
