### ISSUE TITLE
Add YUV 4:4:4 support to PNG

### ISSUE THREAD

**Issue by ProgramMax** [w3c/ColorWeb-CG#16]
During the 2021-02-24 meeting there was interest in supporting narrow range in PNGs. This implies the requirement of YUV support in PNG.

PNG doesn't currently have a way to specify different sizes for different planes. Until that is added, formats like 4:2:0 cannot be used. However, 4:4:4 is a possibility.

**Comment by simontWork** [comment]
Is the issue that to use the CICP Narrow/Nominal flag, that the Matrix Coefficients needed to be present, even for RGB?

If it's not possible to implement YCbCr easily, could we profile Matrix Coefficients to only be equal to the identity matrix (i.e. RGB) and thus allow the narrow range flag to be used?

**Comment by ProgramMax** [comment]
For non-YUV, I think we have a few options:
1.) the field is omitted.
2.) the field must be 0.
3.) the field is ignored.

1 is one less byte for a bit messier parsing.
2 introduces a possible invalid file with no benefit, in my opinion.
3 seems most easy but comes at the cost of a wasted byte for the vast majority of PNGs, I suspect.

I think I'm in favor of 1, giving up the cleaner parsing. But I'm not hard set on that. What do you all think?

**Comment by palemieux** [comment]
> PNG doesn't currently have a way to specify different sizes for different planes. Until that is added, formats like 4:2:0 cannot be used. However, 4:4:4 is a possibility.

I am not aware of widespread use of YCbCr/YUV 4:4:4 -- either YUV 4:2:2 or RGB 4:4:4 is typically used.

**Comment by ProgramMax** [comment]
> I am not aware of widespread use of YCbCr/YUV 4:4:4

Nor am I. While investigating what forms of jpeg there are on the web, I don't recall this being one we worried about.

Any form of chroma subsampling won't work with PNG as-is. The only reason for YUV 4:4:4 is to support narrow range, right?

**Comment by palemieux** [comment]
> The only reason for YUV 4:4:4 is to support narrow range, right?

If so, I wonder if PNG is the right format?

**Comment by palemieux** [comment]
2021-03-16
=======

Much effort needed to add support for YUV to PNG. Orthogonal to HDR support. Will not fix for now.
