### ISSUE TITLE
PNG doc to reference unversioned BT.2100 instead of BT.2100-1?

### ISSUE THREAD

**Issue by ProgramMax** [w3c/ColorWeb-CG#26]
The PNG explicitly references BT.2100-1. I believe we should reference the unversioned BT.2100 instead.

BT.2100-0 specifies HDR using PQ and HLG. So the first claim of "As such, it cannot model the Reference PQ or HLG OOTFs specified in [BT2100-1], which are commonly used for HDR images." seems to be incorrectly versioned.

I believe this is a carry-over from the original proposal https://www.w3.org/TR/png-hdr-pq/ , which references -1 explicitly.

Perhaps this is intentional, as -0 mentions "The Administrations of France and the Netherlands have expressed concerns..." and so perhaps -1 is the first internationally approved version.

**Comment by svgeesus** [comment]
It seems best to reference the unversioned one, in particular so we catch any updates
