### ISSUE TITLE
WebXR, WCG and HDR

### ISSUE THREAD

**Issue by svgeesus** [w3c/ColorWeb-CG#3]
Originally [raised in TAG review of Lab](https://github.com/w3ctag/design-reviews/issues/488#issuecomment-610107610)

**Comment by svgeesus** [comment]
WebXR does not directly define the colorspace used, but does require that rendering be to an HTML `canvas` which implicitly defines what colorspace is used (8bit sRGB).

- [Add a color space as an optional feature for requestSession?](https://github.com/immersive-web/webxr/issues/1140)
- [Are 8-bit outputs sRGB encoded?](https://github.com/immersive-web/webxr/issues/988)

I notice some confusin between the input colorspace, the output colorspace, and the texture format.

**Comment by palemieux** [comment]
Propose to close since, as noted above, [WebXR](https://www.w3.org/TR/webxr/) relies on canvas and canvas is already discussed in the [report](https://w3c.github.io/ColorWeb-CG/#canvas-api).
