### ISSUE TITLE
Add HDR metadata to rec2100-pq canvases

### ISSUE THREAD

**Issue by palemieux** [w3c/ColorWeb-CG#36]
Given the objective:

> To display PQ encoded HDR images and video in a canvas such that PQ images drawn in the canvas will appear exactly the same as they would if displayed via an <img> or <video> tag.

It should be possible for the application to (optionally) associate the following information with a `rec2100-pq` canvas:

## Mastering Display Color Volume Metadata as specified in SMPTE ST 2086

* Mastering Display Primaries: list of 3 (x, y) chromaticity coordinates. Each chromaticity coordinate consists of two uint16 elements, in order, the normalized x and y chromaticity coordinates of the color primary in units of 0.00002

EXAMPLE: Color primaries of the P3D65 system specified in SMPTE ST 2113: `{ 34000, 16000 } { 13250, 34500 } { 7500, 3000 }`

* Mastering Display White Point Chromaticity: (x, y) chromaticity coordinate. Each chromaticity coordinate consists of two uint16 elements, in order, the normalized x and y chromaticity coordinates of the color primary in units of 0.00002

EXAMPLE: Illuminant D65 specified in SMPTE RP 177: `{ 15635, 16450 }`

* Mastering Display Maximum Luminance: uint32 value in units of 0.0001 cd/m<sup>2</sup>

EXAMPLE: Reference white in Recommendation ITU-R BT.2035: `1000000`

* Mastering Display Maximum Luminance: uint32 value in units of 0.0001 cd/m<sup>2</sup>
  
EXAMPLE: Reference black in Recommendation ITU-R BT.2035: `100`

## MaxCLL and MaxFALL as specified in Annex P.1 and P.2 of CTA 861-G

* Maximum Content Light Level: uint16 in units of 1 cd/m<sup>2</sup>

* Maximum Frame-average Light Level: uint16 in units of 1 cd/m<sup>2</sup>

**Comment by ccameron-chromium** [comment]
An API to solve this issue could be

```idl
  interface ColorVolumeMetadata {
    // Color volume in xy coordinates
    float? redPrimary[];
    float? greenPrimary[];
    float? bluePrimary[];

    // Light level, units less clear here.
    float? maxContentLightLevel;
    float? maxFrameAverageLightLevel;
  };
```

And then, to ```CanvasHighDynamicRangeOptions``` add
```idl
  partial interface CanvasHighDynamicRangeOptions {
    ColorVolumeMetadata? color_volume_metadata;
  }
```

Using these, an application would be able to call
```
  myCanvas.configureHighDyanmicRange({
      color_volume_metadata:{maxContentLightLevel:1000}})
```

The units for `maxContentLightLevel` should be nits for PQ content. For `extended-srgb-linear` content, nits is not a good fit. I would say that for such a space, 1.0 should refer to SDR brightness.

**Comment by ccameron-chromium** [comment]
We will also want to add a `configureHighDyanmicRange` method to `OffscreenCanvas`
