### ISSUE TITLE
Luminance gain factor required when compositing SDR bitmaps onto a PQ canvas

### ISSUE THREAD

**Issue by palemieux** [w3c/ColorWeb-CG#39]
The sRGB color space specifies an absolute reference white point luminance of 80 cd∙m<sup>-2</sup>. As a result, colors specified in the sRGB  space cannot be reliably composited with display-referred high-dynamic range (HDR) images, such as those that use the perceptual quantizer electro-optical transfer function (PQ EOTF) specified in Rec. ITU-R BT.2100.

Specifically,
* sRGB colors may appear too dim if they remain unscaled and the average luminance of the scene exceeds 80 cd∙m<sup>-2</sup>; and
* sRGB colors may appear too bright if they are uniformly scaled to an arbitrary large luminance, such as 10,000 cd∙m<sup>-2</sup>.

Suggest following the same approach as used in [TTML2](https://www.w3.org/TR/ttml2/#style-attribute-luminanceGain)

**Comment by svgeesus** [comment]
For PQ, an ITU default value of 203 nits should be the default; and an absolute value (e.g. 100, 300) should be allowed to override this default

80 is known to be too low and 10,000 is clearly way to high and not physically realizable full-screen

**Comment by svgeesus** [comment]
An absolute value, rather than a multiplier on 80 nits, would be easier to deal with
