### ISSUE TITLE
It would be handy to call out (D65) here, rather than having the reader have to double-check.

### ISSUE THREAD

**Issue by palemieux** [w3c/ColorWeb-CG#41]
It would be handy to call out (D65) here, rather than having the reader have to double-check.
It would generally be nice to have parentheticals, so that it's clear when something is e.g. srgb primaries, rather than purely referring to specs.
Referring to specs is great, but it's even better to cache the meaning in non-normative parentheticals, rather than having to dig up specs.

_Originally posted by @jdashg in https://github.com/w3c/ColorWeb-CG/pull/38#discussion_r629692864_

**Comment by ccameron-chromium** [comment]
Added in fixes in https://github.com/w3c/ColorWeb-CG/pull/new/fix-abs

**Comment by ccameron-chromium** [comment]
Added a parenthetical D65 to the references to this white point.
