### ISSUE TITLE
An image editor needs to know the capabilities of the mastering display

### ISSUE THREAD

**Issue by LarsBrg** [w3c/ColorWeb-CG#42]
When color grading images, the user need to know if the image they see is the undistorted image or if the appearance is distorted by the display bounds. 

Non-web image editing apps (such as Photoshop) use the knowledge of the display gamut to 
- highlight which pixels are outside the display gamut.
- map such colors to similar in gamut colors without a huge hue shift.

The same capabilities are required in a web based image editing app.

The application needs this info:
- color primaries and white point
- max luminance or headroom above sRGB white
- min luminance

This is found in the SMPTE ST 2086 parameter set.
Add link here to ST 2086

**Comment by ProgramMax** [comment]
FWIW, I'm not sure this info is always available to apps.
I believe Android doesn't let apps know the display's primaries or white point.

This is why I asked earlier about an app not knowing and simply specifying "This buffer is in this color space. OS/Driver, do with it what you will."

**Comment by ProgramMax** [comment]
Even if the information isn't available, that doesn't mean we shouldn't expose it when we can.
There might be fingerprinting issues.
I just wanted to point out that we might have to return null in some cases.

**Comment by LarsBrg** [comment]
And if so, maybe the app needs to ask the user for some info? Clumsy. 

In Photoshop you can select a proofing target manually.

 

From: Chris Blume ***@***.***>
Reply-To: w3c/ColorWeb-CG ***@***.***>
Date: Monday, May 10, 2021 at 2:37 PM
To: w3c/ColorWeb-CG ***@***.***>
Cc: Lars Borg ***@***.***>, Author ***@***.***>
Subject: Re: [w3c/ColorWeb-CG] An image editor needs to know the capabilities of the mastering display (#42)

 

Even if the information isn't available, that doesn't mean we shouldn't expose it when we can.
There might be fingerprinting issues.
I just wanted to point out that we might have to return null in some cases.

**Comment by svgeesus** [comment]
> There might be fingerprinting issues.

There certainly is, although exposing the peak small-area luminance in a limited number of bins rather than precise values greatly reduces the fingerprint capability. The [VESA Display HDR groups](https://displayhdr.org/performance-criteria-cts1-1/) might be a suitable set of bins: 


400 | 500 | 600 | 1000 | 1400
-- | -- | -- | -- | --

**Comment by chrisn** [comment]
Links to previous discussions on display capability detection for TV devices, where the video plane may have different capabilities to the graphics plane:

* https://github.com/w3c/media-capabilities/issues/118
* https://github.com/w3c/media-capabilities/issues/119
* https://github.com/w3c/csswg-drafts/issues/5044

**Comment by chrisn** [comment]
Also related, for the [Open Screen Protocol](https://w3c.github.io/openscreenprotocol/) that supports the [Remote Playback API](https://w3c.github.io/remote-playback/):

* https://github.com/w3c/openscreenprotocol/issues/194

**Comment by ccameron-chromium** [comment]
Added a [PR](https://github.com/w3c/ColorWeb-CG/pull/62) to address this. It goes in the "just headroom, primaries, and white point" direction. Will require user prompt, built on top of [window placement](https://github.com/webscreens/window-placement/blob/main/EXPLAINER.md).
