### ISSUE TITLE
scRGB-nl to scRGB transformation equation does not appear to be present in IEC 61966-2-2:2003

### ISSUE THREAD

**Issue by michaeldsmith** [w3c/ColorWeb-CG#46]
IEC 61966-2-2:2003 appears to include normative definitions for 

R_scRGB, G_scRGB, B_scRGB as floats in equation (1)
R_scRGB_(16), G_scRGB_(16), B_scRGB_(16) as 16 bit integers in equation (2)

IEC 61966-2-2:2003 contains normative transformations from CIE 1931 XYZ values to 16-bit scRGB values R_scRGB_(16), G_scRGB_(16), B_scRGB_(16) 

IEC 61966-2-2:2003 contains normative transformations from 16-bit scRGB values R_scRGB_(16), G_scRGB_(16), B_scRGB_(16) to CIE 1931 XYZ values

Annex A includes informative transformation between 8-bit sRGB to 16-bit scRGB values

Annex B include informative transformation from scRGB values R_scRGB, G_scRGB, B_scRGB to non-linear values scRGB-nl and its YCC transformation scYCC-nl

IEC 61966-2-2:2003 does not appear to include (normative or informative) a decoding equation for the transformation of scRGB-nl to scRGB linear values R_scRGB, G_scRGB, B_scRGB

**Comment by kenrussell** [comment]
cc'ing @ccameron-chromium
