### ISSUE TITLE
transfer function for extended-sRGB doesn't handle E' less than -0.04045

### ISSUE THREAD

**Issue by michaeldsmith** [w3c/ColorWeb-CG#51]
negative values input to pow(value, exponent) function are not well defined when exponent is not an integer in current definition (exponent = 2.4 is not an integer)
```
   E = | E' / 12.92, if abs(E') ≤ 0.04045
       | ((E' + 0.055) / 1.055)^2.4, otherwise

       with E' ∈ ℝ 
```

Do you want symmetry around 0 but with negative sign for negative input, or do you want the linear segment to just keep going linearly forever into negative output for negative input?  

The if/else below gives symmetry around 0 with negative output for negative input, I think this is what you really want, right?

```
if N < -0.04045
  L = -1.0 * (((-1.0*N) + 0.055) / 1.055)^2.4;
elseif (N >= -0.04045 && N <= 0.04045)
  L  = N / 12.92;
else
  L = ((N + 0.055) / 1.055)^2.4;
end
```

![image](https://user-images.githubusercontent.com/37905569/121102071-e892b680-c7b1-11eb-8f53-d1f2fe0099a7.png)

![image](https://user-images.githubusercontent.com/37905569/121102091-f3e5e200-c7b1-11eb-86c9-2e5b26af13c2.png)

**Comment by svgeesus** [comment]
> Do you want symmetry around 0 but with negative sign for negative input, or do you want the linear segment to just keep going linearly forever into negative output for negative input?

Most implementations mirror around 0. 

For example [CSS Color 4 defines it like this](https://www.w3.org/TR/css-color-4/#valdef-color-srgb):

```js
let sign = c < 0? -1 : 1;
let abs = Math.abs(c);

if (abs < 0.04045) {
  cl = c / 12.92;
}
else {
  cl = sign * (Math.pow((abs + 0.055) / 1.055, 2.4));
}
```

c is the gamma-encoded red, green or blue component. cl is the corresponding linear-light component.

**Comment by svgeesus** [comment]
Note that separating out the sign and then adding it back is important because `pow` is not defined for negative values and will return `NaN`

**Comment by ccameron-chromium** [comment]
Rolled in with https://github.com/w3c/ColorWeb-CG/pull/new/fix-abs

**Comment by ccameron-chromium** [comment]
Thanks -- I've updated this to write the function as Javascript and to fix the missing sign issue in https://github.com/w3c/ColorWeb-CG/pull/70
