### ISSUE TITLE
Should there be a distinct extended-srgb color space, or should srgb be extended by default?

### ISSUE THREAD

**Issue by ccameron-chromium** [w3c/ColorWeb-CG#65]
My understanding is that our answer has been "yes, srgb should be extended by default", but I'd like to ventilate the issue.

The non-extended sRGB has a transfer function that is defined only on the [0, 1] interval. Its definition is
```math
   T(x) = { x / 12.92                  : if 0 ≤ x ≤ 0.04045
          { ((x + 0.055) / 1.055)^2.4  : if x < 0.4045 ≤ 1
```

The extended sRGB transfer function is defined on all real numbers by point symmetry around the origin. In particular,
```math
   T(x) = { x / 12.92                                 : if abs(x) ≤ 0.04045
          { sign(x) * ((abs(x) + 0.055) / 1.055)^2.4  : otherwise
```

This comes up in the following settings:
* What if we write values outside of [0, 1] to a WebGL or WebGPU canvas?
  * Should we clamp values to [0, 1], or should we allow them to express colors outside of the sRGB gamut?
* What if we upload a wide color gamut image to a floating-point `srgb` WebGL or WebGPU texture?
  * Should we clamp to texture color values [0, 1]?

The [proposal](https://github.com/w3c/ColorWeb-CG/blob/master/hdr_html_canvas_element.md) currently introduces a `extended-srgb` and a `extended-linear-srgb` color space. If we resolve that `srgb` should be extended by default, then they should be changed to `srgb` and `linear-srgb`.

**Comment by palemieux** [comment]
Per 2021-07-19: change extended-srgb to srgb. Add table illustrating the combinations of floating/integer representation and color spaces.

**Comment by ccameron-chromium** [comment]
I've updated this in the spec. There was wide consensus regarding this issue in the most recent call that srgb should be defined on all real numbers, and should not have a separate "extended" version.

For some color spaces like rec2100-hlg and rec2100-pq, there is no reasonable extension of the function to all real numbers.

For other color spaces (e.g, display-p3, and other things we may consider later like Lab or rec2020), this is to be decided on a case-by-case basis.
