### ISSUE TITLE
HDR-in-PNG: should BT.2100 full range be one of the recommended color spaces?

### ISSUE THREAD

**Issue by 13thsymphony** [w3c/ColorWeb-CG#68]
The [strawman](https://github.com/w3c/ColorWeb-CG/blob/master/hdr-in-png-requirements.md#strawman-approach) links to [ITU-T Series H Supplement 19](https://www.itu.int/rec/T-REC-H.Sup19-201910-I) presumably as a convenient reference to the most important color space combinations that are recommended to be used. It doesn't appear that BT.2100 full range is one of the combinations in that spec. BT.2100 full range is the color space used in the [previous method](https://www.w3.org/TR/png-hdr-pq/) and is likely the most important single color space for computer-generated content, e.g. screen captures of games and apps.

**Comment by palemieux** [comment]
The cICP chunk is intended to support all combinations specified in H.273, which includes full range image.

ITU-T Series H Supplement 19 is only an informative reference.

**Comment by 13thsymphony** [comment]
OK, thanks for the clarification!
