### ISSUE TITLE
Application tone mapping in HDR Canvas API

### ISSUE THREAD

**Issue by donmccurdy** [w3c/ColorWeb-CG#79]
In the use cases and examples described by the "Canvas High Dynamic Range" proposal, I'm mostly reading descriptions of how to display existing HDR content, such as images and video. Use of the proposal for image formation in computer-generated imagery (CGI) and physically-based rendering (PBR) is not explicitly discussed. Consider a mixed 3D scene with various objects and light sources,  resulting in an image that [benefits from wider dynamic range](https://www.creativeshrimp.com/filmic-blender-tutorial.html).

Is this roughly an intended workflow for such applications?

1. Application render pass outputs pixels to frame buffer in open domain [0, ∞], float-16, Linear-sRGB<sup>1</sup> 
2. Application tone mapping pass applies a view transform (e.g. [Filmic](https://sobotka.github.io/filmic-blender/)), output is again open domain [0, ∞], float-16, Linear-sRGB, with high intensity values significantly compressed
3. Depending on device / platform capabilities:
    - a. For SDR display, output to canvas with `mode = 'default'`, pixel values in closed domain [0,1] sRGB
    - b. For HDR display, output to canvas with `mode = 'extended'`, sRGB, pixel values in open domain [0, ∞] sRGB

Does this seem correct? In particular, I assume such an application will often want to _avoid_ having a generic tone map performed by the platform or display device, as in the `rec2100-pq` and `rec2100-hlg` cases? Is it possible to output to a wider color gamut like P3, without enabling one of these two HDR color spaces? I only see extended sRGB discussed here, not extended Display P3, and do not know if there are active plans to bring Display P3 to WebGL.

> **UPDATE 2024-10-14:** My strawman workflow above is not, in retrospect, correct. A better workflow could perhaps be implemented by changes to tone mapping, targeting Rec. 2100 HLG output and with some adjustments to color grading. With output to Extended sRGB our image formation will be problematic, in ways that I suspect are fundamental.

***

<sup>1</sup> Definitions:

- **Linear-sRGB:** Linear / Rec. 709 / D65
- **sRGB:** sRGB / Rec. 709 / D65

**Comment by palemieux** [comment]
@donmccurdy See the proposed `rec2100-display-linear` space at https://github.com/w3c/ColorWeb-CG/blob/feature/add-mastering-display-info/hdr_html_canvas_element.md .

**Comment by donmccurdy** [comment]
Thank you! I think I will need to learn more about how tone mapping is implemented for an HDR display, my steps 1-3 above do not feel quite correct to me now. But that is probably outside scope here.

What does the "display" term in `rec2100-display-linear` / `rec2100-linear-display`[^1] refer to? I think I would have expected this predefined colorspace to be `rec2100-linear`, but have probably missed something.

[^1]: Current draft refers to both, likely a typo.

**Comment by palemieux** [comment]
> What does the "display" term in rec2100-display-linear / rec2100-linear-display[1](https://github.com/w3c/ColorWeb-CG/issues/79#user-content-fn-1-5cc27f1d279d2ea9c78b925eb4e01076) refer to?

The _display_ qualifier emphasizes that the component signals are display-referred, i.e., R = G = B = 1 means 203 nits on the Rec. 2100 reference display.

**Comment by donmccurdy** [comment]
I think we can close this issue – thanks! My original question had some wrong assumptions, and in any case the image formation pipelines used in 3D rendering pipelines on the web are admittedly outside of scope for this repo.

Noting that HDR support in WebGPU shipped in Chrome 129, with Extended sRGB and Extended Display P3 as available drawing buffer color spaces... there are some issues preventing a library like three.js (to which I contribute) from being able to implement color managed rendering using WebGPU's HDR support. But I suspect these are WebGPU spec-related issues, and will continue in a new issue:

- https://github.com/gpuweb/gpuweb/issues/4919
