### ISSUE TITLE
Charter

### ISSUE THREAD

**Issue by annevk** [w3c/ColorWeb-CG#88]
Does this CG have a charter? I wasn't able to find one.

**Comment by palemieux** [comment]
Will work with @svgeesus to locate or create one.

**Comment by svgeesus** [comment]
It does not have one, but several people have requested it.

**Comment by annevk** [comment]
@svgeesus @palemieux https://w3c.github.io/ColorWeb-CG/charter.html still says [DRAFT]. Is that intentional? It should probably also be linked from https://www.w3.org/community/colorweb/ or somewhere?

**Comment by palemieux** [comment]
The charter will be accepted (save for last minute objections) on 2022-12-12 per https://lists.w3.org/Archives/Public/public-colorweb/2022Dec/0006.html. I plan to remove the _draft_ label at that point.

I like the idea of linking it from the CG's web page, assuming this is possible.

**Comment by nigelmegitt** [comment]
The link from that email is wrong. This one works: http://htmlpreview.github.io/?https://github.com/w3c/ColorWeb-CG/blob/main/charter.html

**Comment by annevk** [comment]
Thanks, that's great. (As for the link, I'd recommend using the link I used above.)
