### ISSUE TITLE
Charter claims to be a work in progress

### ISSUE THREAD

**Issue by jyasskin** [w3c/ColorWeb-CG#96]
https://w3c.github.io/ColorWeb-CG/charter.html says "This Charter is work in progress", but https://github.com/w3c/ColorWeb-CG/issues/88#issuecomment-1341162631 says it's accepted by now. Could y'all update the text?

**Comment by palemieux** [comment]
Done at 233778626a3cecc9731cf568d6bba562dca1f0b8
